# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            User Logged In
tagline:          'Felt Cute Will Delete Later'
description:      'hacking & ⚑ ⚑ ⚑.'
url:              http://localhost:4000
baseurl:          /
author:
  name:           'userloggedin'
  url:            https://twitter.com/bestbuypayphone

paginate:         5

# Custom vars
version:          0.0.🖕

github:
  repo:           https://github.com/bernardr
